#macro CHAR_SOM_NAME_LONG "Soma Cruz"					   
#macro CHAR_ALU_NAME_LONG "Alucard"						   
#macro CHAR_JON_NAME_LONG "Jonathan Morris"				   
#macro CHAR_JUL_NAME_LONG "Julius Belmont"				   
#macro CHAR_RIC_NAME_LONG "Richter Belmont"				   
#macro CHAR_SHA_NAME_LONG "Shanoa"						   
#macro CHAR_CHA_NAME_LONG "Charlotte Aulin"				   
#macro CHAR_YOK_NAME_LONG "Yoko Belnades"				   
#macro CHAR_MAR_NAME_LONG "Maria Renard"				   
#macro CHAR_SIM_NAME_LONG "Simon Belmont"				   
#macro CHAR_FUM_NAME_LONG "Getsu Fuma"					   

#macro CHAR_SOM_NAME_SHORT "Soma"							
#macro CHAR_ALU_NAME_SHORT "Alucard"							
#macro CHAR_JON_NAME_SHORT "Jonathan"						
#macro CHAR_JUL_NAME_SHORT "Julius"							
#macro CHAR_RIC_NAME_SHORT "Richter"							
#macro CHAR_SHA_NAME_SHORT "Shanoa"							
#macro CHAR_CHA_NAME_SHORT "Charlott"						
#macro CHAR_YOK_NAME_SHORT "Yoko"							
#macro CHAR_MAR_NAME_SHORT "Maria"							
#macro CHAR_SIM_NAME_SHORT "Simon"							
#macro CHAR_FUM_NAME_SHORT "Fuma"							

#macro MENU_STAGE_CHAPNUM "Chapter "
#macro MENU_STAGE_DIFF_NORM  "Normal"
#macro MENU_STAGE_DIFF_HARD  "Hard"
#macro MENU_STAGE_DIFF_HELL  "Hell"
#macro MENU_STAGE_NAME1   "Caught in the Cradle of Decay"
#macro MENU_STAGE_NAME2   "Lord of Unseen Strings"
#macro MENU_STAGE_NAME3   "The End of Chaos"
#macro MENU_STAGE_NAME4   "Esquisse of Violence"
#macro MENU_STAGE_NAME5   "Song of the Unslakable Blade"
#macro MENU_STAGE_NAME6   "Come, Sweet Hour of Death"
#macro MENU_STAGE_NAME7   "Beauty, Desire, Situation Dire"
#macro MENU_STAGE_NAME8   "The One Who Is Many"
#macro MENU_STAGE_NAME9   "Lord of Flies"
#macro MENU_STAGE_NAME10  "Origins"
#macro MENU_STAGE_NAME11  "The Legend of Fuma"

#macro MENU_PAGENAME_LOCAL "Local Play"
#macro MENU_PAGENAME_ONLINE "Online Play"
#macro MENU_PAGENAME_CHARCHANGE "Select Character"
#macro MENU_PAGENAME_CHARCOLOR "Choose a character color."
#macro MENU_PAGENAME_CHAPCHANGE "Select a Chapter"
#macro MENU_PAGENAME_OFFGEAR "Offensive Gear"
#macro MENU_PAGENAME_DEFGEAR "Defensive Gear"
#macro MENU_PAGENAME_MARTARTS "Martial Arts"
#macro MENU_PAGENAME_MONCOMP "Monster Compendium"
#macro MENU_PAGENAME_ITEMCOMP "Item Compendium"
#macro MENU_PAGENAME_CONTSETT "Controller Settings"
#macro MENU_PAGENAME_SNDSETT "Sound Settings"
#macro MENU_PAGENAME_WNDWSETT "Window Settings"
#macro MENU_PAGENAME_SCRNSETT "Screen Settings"
#macro MENU_PAGENAME_CMRASETT "Camera Settings"

#macro MENU_OPTIONS_ONLINE_COOP "Co-op Mode"
#macro MENU_OPTIONS_ONLINE_SURVIVAL "Survival Mode"

#macro MENU_OPTIONS_COOP_QUICKMATCH "Quick Match"
#macro MENU_OPTIONS_COOP_CUSTOMMATCH "Custom Match"
#macro MENU_OPTIONS_COOP_CREATEMATCH "Create a Team"






#macro MENU_FLAVOR_LOCALPLAY "Play locally"
#macro MENU_FLAVOR_CHARCHANGE "Select a character to play as."
#macro MENU_FLAVOR_CHAPCHANGE "Select a chapter to play."
#macro MENU_FLAVOR_EQUIPCHANGE "Change equipment and game options."
#macro MENU_FLAVOR_SHOP "Purchase weapons, armor, and items."
#macro MENU_FLAVOR_STARTGAME "Begin playing the selected chapter."
#macro MENU_FLAVOR_CHARCHANGE_INNER "Select a character to play as."
#macro MENU_FLAVOR_CHAPCHANGE_INNER "Select the cahpter you want to take on."
#macro MENU_FLAVOR_OFFGEAR "Change your weapons and magic."
#macro MENU_FLAVOR_DEFGEAR "Change your armor and equipped item."
#macro MENU_FLAVOR_GEARINNER "Select the equipment to change"
#macro MENU_FLAVOR_GEARLIST "Select from the list"
#macro MENU_FLAVOR_MARTARTS "View a list of Martial Arts you can use."
#macro MENU_FLAVOR_MONCOMP "View a list of monsters you have encountered in the game."
#macro MENU_FLAVOR_MONCOMP_INNER "Monster Compendium"
#macro MENU_FLAVOR_ITEMCOMP "View a list of items you have obtained."
#macro MENU_FLAVOR_ITEMCOMP_INNER "Item Compendium"
#macro MENU_FLAVOR_CONTSETT "Change your button settings."
#macro MENU_FLAVOR_SNDSETT "Change sound settings."
#macro MENU_FLAVOR_WNDWSETT "Change window color and transparency."
#macro MENU_FLAVOR_SCRNSETT "Change screen settings."
#macro MENU_FLAVOR_CMRASETT "Customize zoom and transition time."
#macro MENU_FLAVOR_SETT_DEFAULT "Restore the default settings."
#macro MENU_FLAVOR_SETT_CONFIRM "Accept these settings and exit."




